
[build]
  base = "packages/webapp"
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev-vite"
  targetPort = 5173

[functions]
  directory = "src/functions"

[[redirects]]
  from = "/game/:gameId"
  to = "/"
  status = 200

[[redirects]]
  from = "/god/:gameId"
  to = "/"
  status = 200

[[redirects]]
  from = "/god"
  to = "/"
  status = 200

[[redirects]]
  from = "/profile/*"
  to = "/"
  status = 200

[[redirects]]
  from = "/login"
  to = "/"
  status = 200